
version: "3"
services:
  etcd-cl:
    restart: always
    build:
       context: .
    command: ["--listen-peer-urls","http://0.0.0.0:2380","--listen-client-urls","http://0.0.0.0:2379","--advertise-client-urls","http://127.0.0.1:2379"]
    networks:
      - etcd-cluster 

networks:
  etcd-cluster:
