
version: "2"
services:
  teampass-db:
    restart: always
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 4dm1nSd1g1tS 
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: t34mP4sSw0rD 
      MYSQL_USER: teampassApp 
  teampass-app:
    restart: always
    build:
       context: .
       dockerfile: Dockerfile.web
    ports:
      - "80:80"
    links:
      - teampass-db:db
    depends_on:
      - teampass-db
