pipeline {
    agent any
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    stages {
        stage('Build container'){
            script: '''
                set +x
                cd jenkins
                docker build -t test-alpine -f Dockerfile.alpine .
            ''''
        }
    }
}