pipeline {
    agent any
    environment{
        DUMMY = ''
    }
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    stages {
        stage('Build container'){
            steps{
                sh script: """
                    set +x
                    cd jenkins
                    docker build -t test-alpine -f Dockerfile.alpine .
                """
            }
        }
    }
}