#Docker compose file for EFK stack deployment

version: '2.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: es-cl0-1
    mem_limit: 1000M
    mem_reservation: 750M
    cpu_count: 1
    #cpu_percent: 50
    environment:
      - cluster.name=es-cl0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- "discovery.zen.ping.unicast.hosts=es-cl0-1,es-cl0-2"
      - "discovery.zen.ping.unicast.hosts=es-cl0-1"
      #Parameters only for NAT or proxied hosts ( remove network.host and transport.host parameters )
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=es-cl0-1"
      - "transport.bind_host=0.0.0.0"
      - "transport.publish_host=es-cl0-1"
      - "xpack.monitoring.history.duration=1d"
    #sysctls:
    #  - vm.max_map_count=262144
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-cl0-1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-cl0-net  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: es-cl0-kibana
    mem_limit: 500M
    mem_reservation: 400M
    cpu_count: 1
    #cpu_percent: 50
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://es-cl0-1:9200
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch
      #- elasticsearch2
    networks:
      - es-cl0-net
  fluentd:
    build:
      context: dockerfiles/fluentd
    container_name: log-shipper
    mem_limit: 150M
    mem_reservation: 100M
    cpu_count: 1
    #cpu_percent: 50
    volumes:
      - /var/lib/docker:/data:ro
      - ./conf/fluentd.conf:/fluentd/etc/fluentd-alt.conf:ro
    environment:
      - FLUENTD_CONF=fluentd-alt.conf
      #- FLUENTD_OPT="-vv"
      - FLUENT_UID=1
    ports:
      - 24224:24224
    depends_on:
      - elasticsearch
    networks:
      - es-cl0-net  
volumes:
  es-cl0-1-data:
    driver: local
  #es-cl0-2-data:
  #  driver: local

networks:
  es-cl0-net:
