FROM openjdk:8-slim

RUN apt-get update && apt-get -y install curl apt-transport-https uuid-runtime pwgen \
    && curl -sL -o graylog-2.4-repository_latest.deb https://packages.graylog2.org/repo/packages/graylog-2.4-repository_latest.deb \
    && dpkg -i graylog-2.4-repository_latest.deb \
    && apt-get update \
    && apt-get -y install graylog-server 
