COMPONENTS_VERSION=v1.5.1

# Directories variables
HARBOR_DATA_DIR=./data
HARBOR_CONFIG_DIR=./config
HARBOR_LOG_DIR=./log
HARBOR_OVERRIDE_DIR=./override

# Secret variables ( set before building environment )
SECRET_HARBOR_ADMIN_PASSWORD="12345678"

export COMPONENTS_VERSION 
export HARBOR_DATA_DIR HARBOR_CONFIG_DIR HARBOR_LOG_DIR HARBOR_OVERRIDE_DIR
export SECRET_HARBOR_ADMIN_PASSWORD